---
title: "Lab1"
author: "Kathryn Denning, Karlena Ochoa, Tamara Niella"
date: "1/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, echo = FALSE, warning = FALSE, message=FALSE, error=FALSE}

library(rio)
library(here)
library(tidyverse)
library(magrittr)

# setting global options: 

knitr::opts_chunk$set()

```

```{r read and explore data}
df <- import(here("data","rstats_tweets.rds"))
head(df)
str(df)
```

Commit 2
```{r fig.width=10, fig.height=10}
df2 <- df %>% count(screen_name) %>%
  arrange(desc(n)) %>% 
  slice(1:25)

df2 %<>% mutate(screen_name = as.factor(screen_name)) %>%  
  mutate(screen_name = fct_reorder(screen_name, n))

ggplot(df2, aes(screen_name,n)) + 
  geom_col() +
  coord_flip()+
  theme_minimal(base_size = 15)

```
Commit 3
```{r}
knitr::opts_chunk$set(fig.width = 10, fig.height = 10) 

ggplot(df2, aes(screen_name,n)) + 
  geom_col(fill= "cornflowerblue") +
  coord_flip()+
  labs(title= "Most prolific #rstats tweeters", 
       subtitle = "Top 25 screen names displayed", 
       x = "Twitter Screen Name", y = "Count", caption= "Data from Mike Kearny, distributed via #tidytuesday")+
  theme_minimal(base_size = 15)

```
Commit 4
```{r}
df4 <- df %>%
  select(created_at) %>% 
  mutate(month = lubridate::round_date(created_at, unit = "month")) %>% 
  filter(month < lubridate::as_datetime("2019-01-01 00:00:00")) %>% 
  count(month)
  
plot4 <- ggplot(df4, aes(x = month, y = n)) + 
  geom_line() +
  geom_smooth()

plot4

```

Commit 5
```{r}
theme_set(theme_minimal(base_size = 16))
knitr::opts_chunk$set(fig.width = 10, fig.height = 10) 
plot5 <- ggplot(df4, aes(x = month, y = n)) + 
  geom_area(fill = "cornflowerblue", alpha = 0.3) +
  geom_line(color="gray40") +
  geom_smooth(se=FALSE, color="magenta") +
  labs(title= "Growth of #rstats hashtag on twitter over time", 
       x = "Year (data summarized by month)", 
       y = "Number of #rstats tweets",
       caption = "Data from Mike Kearney, distributed via #tidytuesday")
plot5
```
